---

- name: install apache
  apt:
    name: "{{ apache_dependencies }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: [apt, packages, apache]

- name: start/enable apache
  service:
    name: "apache2"
    state: started
    enabled: yes
  tags: [services, apache]

- name: configure the apache default site
  template:
    dest: "/etc/apache2/sites-available/000-default.conf"
    src: "default-http.conf.j2"
  notify: restart apache
  tags: [config, templates, apache]

- name: make sure the document root exists
  file:
    path: "{{ document_root }}"
    state: directory
  tags: [files, apache]

- name: make sure an index.html is present in the document root
  copy:
    dest: "{{ document_root }}/index.html"
    content: ""
    force: no
  tags: [files, apache]
