---

apt_distribution_release: "{{ ansible_distribution_release }}"

apt_standard_repos:
  - "deb http://ftp.de.debian.org/debian/ {{ apt_distribution_release }} main contrib non-free"
  - "deb http://ftp.de.debian.org/debian/ {{ apt_distribution_release }}-updates main contrib non-free"
  - "deb http://security.debian.org/ {{ apt_distribution_release }}-security main contrib non-free"
  - "deb http://ftp.de.debian.org/debian/ {{ apt_distribution_release }}-backports main contrib non-free"

apt_essential_packages:
  - ansible
  - bind9-host
  - htop
  - iotop
  - nmap
  - bash-completion
  - screen
  - lm-sensors
  - hddtemp
  - hdparm
  - rsync
  - python3-apt
  - git

apt_unwanted_packages:
  - laptop-detect
  - os-prober
  - nano

apt_unattended_upgrades: false

ssh_pubkeys: []

sshd_port: 22
sshd_permit_root_login: "without-password"
sshd_password_authentication: "no"
sshd_host_key_size: 4096
sshd_host_key_algos:
 - "ed25519"
 - "rsa"
sshd_use_dns: false
sshd_x11_forwarding: false
sshd_additional_options: null

use_ntp: true
