---

fqdn: "{{ ansible_fqdn }}"
document_root: "/var/www/html"
ssl_ciphers: "ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA"

apache_admin_email: "michik+apacheadmin@michik.net"
apache_ssl_protos: "All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1"
