---

# Install and configure the Dovecot IMAP server

- name: install dovecot-antispam
  apt: name=dovecot-antispam state=present
  tags: [apt, packages, dovecot]

- name: dovecot antispam configuration
  template:
    src: "90-plugin-antispam.conf.j2"
    dest: "/etc/dovecot/conf.d/90-plugin-antispam.conf"
  notify: restart dovecot
  tags: [config, dovecot]
