---

- name: install spamassassin
  apt: name=spamassassin state=present
  tags: [apt, packages, spamassassin]

- name: stop/disable spamd
  service: name=spamassassin state=stopped enabled=no
  tags: [service, spamassassin]

- name: configure spamassassin
  template:
    src: "local.cf.j2"
    dest: "/etc/spamassassin/local.cf"
  tags: [config, spamassassin]

- name: enable spamassassin cronjob
  lineinfile:
    dest: "/etc/cron.daily/spamassassin"
    regexp: "^CRON="
    line: "CRON=1"
    state: present
  tags: [config, spamassassin]
