---

fqdn: "{{ ansible_fqdn }}"
ssl_ciphers: "ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA"
dh_param_length: 4096

dovecot_mail_location: "maildir:~/Maildir"
dovecot_ssl_protocols: "!SSLv2 !SSLv3 !TLSv1 !TLSv1.1"
